import "./globals.css";
import { Syne } from "next/font/google";
import { ReactLenis } from "lenis/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const syne = Syne({
  subsets: ["latin"],
  weight: ["400", "500", "700", '800'],
  variable: "--font-syne",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${syne.variable}`}>
        {/* <ReactLenis root> */}
          <main className="main">
            {children}
          </main>
        {/* </ReactLenis> */}
      </body>
    </html>
  );
}
